var hierarchy =
[
    [ "MPZT.GUI.Logic.ApiClient", "class_m_p_z_t_1_1_g_u_i_1_1_logic_1_1_api_client.html", null ],
    [ "ApiController", null, [
      [ "MPZT.Api.Controllers.AccountController", "class_m_p_z_t_1_1_api_1_1_controllers_1_1_account_controller.html", null ],
      [ "MPZT.Api.Controllers.AreaController", "class_m_p_z_t_1_1_api_1_1_controllers_1_1_area_controller.html", null ],
      [ "MPZT.Api.Controllers.ConceptController", "class_m_p_z_t_1_1_api_1_1_controllers_1_1_concept_controller.html", null ],
      [ "MPZT.Api.Controllers.ProjectController", "class_m_p_z_t_1_1_api_1_1_controllers_1_1_project_controller.html", null ]
    ] ],
    [ "MPZT.Infrustructure.ModelDto.AreaDto", "class_m_p_z_t_1_1_infrustructure_1_1_model_dto_1_1_area_dto.html", null ],
    [ "MPZT.GUI.Models.AreaModel", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_area_model.html", null ],
    [ "MPZT.GUI.Models.AreaProjectModel", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_area_project_model.html", null ],
    [ "MPZT.GUI.Models.AreaProposalsModel", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_area_proposals_model.html", null ],
    [ "MPZT.Infrastructure.Test.AreaRepositoryTests", "class_m_p_z_t_1_1_infrastructure_1_1_test_1_1_area_repository_tests.html", null ],
    [ "MPZT.Infrastructure.Test.AreaServiceTests", "class_m_p_z_t_1_1_infrastructure_1_1_test_1_1_area_service_tests.html", null ],
    [ "Tests.AreaTests", "class_tests_1_1_area_tests.html", null ],
    [ "AuthorizeAttribute", null, [
      [ "MPZT.GUI.CustomAuthentication.CustomAuthorizeAttribute", "class_m_p_z_t_1_1_g_u_i_1_1_custom_authentication_1_1_custom_authorize_attribute.html", null ]
    ] ],
    [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ],
    [ "MPZT.Infrustructure.ModelDto.CommentDto", "class_m_p_z_t_1_1_infrustructure_1_1_model_dto_1_1_comment_dto.html", null ],
    [ "MPZT.GUI.Models.CommentModel", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_comment_model.html", null ],
    [ "MPZT.Infrastructure.Test.CommentRepositoryTests", "class_m_p_z_t_1_1_infrastructure_1_1_test_1_1_comment_repository_tests.html", null ],
    [ "Controller", null, [
      [ "MPZT.GUI.Controllers.AccountController", "class_m_p_z_t_1_1_g_u_i_1_1_controllers_1_1_account_controller.html", null ],
      [ "MPZT.GUI.Controllers.BaseController", "class_m_p_z_t_1_1_g_u_i_1_1_controllers_1_1_base_controller.html", [
        [ "MPZT.GUI.Controllers.AreaController", "class_m_p_z_t_1_1_g_u_i_1_1_controllers_1_1_area_controller.html", null ],
        [ "MPZT.GUI.Controllers.ConceptController", "class_m_p_z_t_1_1_g_u_i_1_1_controllers_1_1_concept_controller.html", null ],
        [ "MPZT.GUI.Controllers.ProjectController", "class_m_p_z_t_1_1_g_u_i_1_1_controllers_1_1_project_controller.html", null ]
      ] ],
      [ "MPZT.GUI.Controllers.ErrorController", "class_m_p_z_t_1_1_g_u_i_1_1_controllers_1_1_error_controller.html", null ],
      [ "MPZT.GUI.Controllers.HomeController", "class_m_p_z_t_1_1_g_u_i_1_1_controllers_1_1_home_controller.html", null ],
      [ "MPZT.GUI.Controllers.OfficeController", "class_m_p_z_t_1_1_g_u_i_1_1_controllers_1_1_office_controller.html", null ]
    ] ],
    [ "MPZT.GUI.Models.CustomSerializeModel", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_custom_serialize_model.html", null ],
    [ "MPZT.Core.Domain.EntityBase", "class_m_p_z_t_1_1_core_1_1_domain_1_1_entity_base.html", [
      [ "MPZT.Core.Domain.AreaMPZT", "class_m_p_z_t_1_1_core_1_1_domain_1_1_area_m_p_z_t.html", null ],
      [ "MPZT.Core.Domain.Comment", "class_m_p_z_t_1_1_core_1_1_domain_1_1_comment.html", null ],
      [ "MPZT.Core.Domain.GeoPoint", "class_m_p_z_t_1_1_core_1_1_domain_1_1_geo_point.html", null ],
      [ "MPZT.Core.Domain.Location", "class_m_p_z_t_1_1_core_1_1_domain_1_1_location.html", null ],
      [ "MPZT.Core.Domain.Office", "class_m_p_z_t_1_1_core_1_1_domain_1_1_office.html", null ],
      [ "MPZT.Core.Domain.Phase", "class_m_p_z_t_1_1_core_1_1_domain_1_1_phase.html", null ],
      [ "MPZT.Core.Domain.Project", "class_m_p_z_t_1_1_core_1_1_domain_1_1_project.html", null ],
      [ "MPZT.Core.Domain.Proposal", "class_m_p_z_t_1_1_core_1_1_domain_1_1_proposal.html", null ],
      [ "MPZT.Core.Domain.Role", "class_m_p_z_t_1_1_core_1_1_domain_1_1_role.html", null ],
      [ "MPZT.Core.Domain.User", "class_m_p_z_t_1_1_core_1_1_domain_1_1_user.html", [
        [ "MPZT.Core.Domain.OfficeMember", "class_m_p_z_t_1_1_core_1_1_domain_1_1_office_member.html", null ]
      ] ]
    ] ],
    [ "MPZT.Infrustructure.ModelDto.GeoPointDto", "class_m_p_z_t_1_1_infrustructure_1_1_model_dto_1_1_geo_point_dto.html", null ],
    [ "MPZT.GUI.Models.GeoPointModel", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_geo_point_model.html", null ],
    [ "MPZT.Infrastructure.Test.GeopointRepositoryTests", "class_m_p_z_t_1_1_infrastructure_1_1_test_1_1_geopoint_repository_tests.html", null ],
    [ "MPZT.Infrustructure.ModelDto.GeoPointSearchDto", "class_m_p_z_t_1_1_infrustructure_1_1_model_dto_1_1_geo_point_search_dto.html", null ],
    [ "MPZT.GUI.Models.GeoPointSearchModel", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_geo_point_search_model.html", null ],
    [ "HttpApplication", null, [
      [ "MPZT.Api.WebApiApplication", "class_m_p_z_t_1_1_api_1_1_web_api_application.html", null ],
      [ "MPZT.GUI.MvcApplication", "class_m_p_z_t_1_1_g_u_i_1_1_mvc_application.html", null ]
    ] ],
    [ "MPZT.Infrustructure.Services.IAreaService", "interface_m_p_z_t_1_1_infrustructure_1_1_services_1_1_i_area_service.html", [
      [ "MPZT.Infrustructure.Services.AreaService", "class_m_p_z_t_1_1_infrustructure_1_1_services_1_1_area_service.html", null ]
    ] ],
    [ "MPZT.Core.Repositories.IDataRepository< T >", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_data_repository.html", null ],
    [ "MPZT.Core.Repositories.IDataRepository< AreaMPZT >", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_data_repository.html", [
      [ "MPZT.Core.Repositories.IAreaRepository", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_area_repository.html", [
        [ "MPZT.Infrustructure.Repositories.AreaRepository", "class_m_p_z_t_1_1_infrustructure_1_1_repositories_1_1_area_repository.html", null ]
      ] ]
    ] ],
    [ "MPZT.Core.Repositories.IDataRepository< Comment >", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_data_repository.html", [
      [ "MPZT.Core.Repositories.ICommentRepository", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_comment_repository.html", [
        [ "MPZT.Infrustructure.Repositories.CommentRepository", "class_m_p_z_t_1_1_infrustructure_1_1_repositories_1_1_comment_repository.html", null ]
      ] ]
    ] ],
    [ "MPZT.Core.Repositories.IDataRepository< GeoPoint >", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_data_repository.html", [
      [ "MPZT.Core.Repositories.IGeoPointRepository", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_geo_point_repository.html", [
        [ "MPZT.Infrustructure.Repositories.GeoPointRepository", "class_m_p_z_t_1_1_infrustructure_1_1_repositories_1_1_geo_point_repository.html", null ]
      ] ]
    ] ],
    [ "MPZT.Core.Repositories.IDataRepository< Location >", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_data_repository.html", [
      [ "MPZT.Core.Repositories.ILocationRepository", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_location_repository.html", [
        [ "MPZT.Infrustructure.Repositories.LocationRepository", "class_m_p_z_t_1_1_infrustructure_1_1_repositories_1_1_location_repository.html", null ]
      ] ]
    ] ],
    [ "MPZT.Core.Repositories.IDataRepository< Project >", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_data_repository.html", [
      [ "MPZT.Core.Repositories.IProjectRepository", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_project_repository.html", [
        [ "MPZT.Infrustructure.Repositories.ProjectRepository", "class_m_p_z_t_1_1_infrustructure_1_1_repositories_1_1_project_repository.html", null ]
      ] ]
    ] ],
    [ "MPZT.Core.Repositories.IDataRepository< Proposal >", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_data_repository.html", [
      [ "MPZT.Core.Repositories.IProposalRepository", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_proposal_repository.html", [
        [ "MPZT.Infrustructure.Repositories.ProposalRepository", "class_m_p_z_t_1_1_infrustructure_1_1_repositories_1_1_proposal_repository.html", null ]
      ] ]
    ] ],
    [ "IDependencyResolver", null, [
      [ "MPZT.Api.ioc.UnityResolver", "class_m_p_z_t_1_1_api_1_1ioc_1_1_unity_resolver.html", null ]
    ] ],
    [ "IDisposable", null, [
      [ "MPZT.GUI.Logic.Interface.IUserPasswordManager", "interface_m_p_z_t_1_1_g_u_i_1_1_logic_1_1_interface_1_1_i_user_password_manager.html", [
        [ "MPZT.GUI.Logic.UserPasswordManager", "class_m_p_z_t_1_1_g_u_i_1_1_logic_1_1_user_password_manager.html", null ]
      ] ]
    ] ],
    [ "IPrincipal", null, [
      [ "MPZT.GUI.CustomAuthentication.CustomPrincipal", "class_m_p_z_t_1_1_g_u_i_1_1_custom_authentication_1_1_custom_principal.html", null ]
    ] ],
    [ "MPZT.Core.Repositories.IProjectFileRepository", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_project_file_repository.html", [
      [ "MPZT.Infrustructure.Repositories.ProjectFileRepository", "class_m_p_z_t_1_1_infrustructure_1_1_repositories_1_1_project_file_repository.html", null ]
    ] ],
    [ "MPZT.Infrustructure.Services.IProjectService", "interface_m_p_z_t_1_1_infrustructure_1_1_services_1_1_i_project_service.html", [
      [ "MPZT.Infrustructure.Services.ProjectService", "class_m_p_z_t_1_1_infrustructure_1_1_services_1_1_project_service.html", null ]
    ] ],
    [ "MPZT.Infrustructure.Services.IProposalService", "interface_m_p_z_t_1_1_infrustructure_1_1_services_1_1_i_proposal_service.html", [
      [ "MPZT.Infrustructure.Services.ProposalService", "class_m_p_z_t_1_1_infrustructure_1_1_services_1_1_proposal_service.html", null ]
    ] ],
    [ "MPZT.Core.Repositories.IUserRepository", "interface_m_p_z_t_1_1_core_1_1_repositories_1_1_i_user_repository.html", [
      [ "MPZT.Infrustructure.Repositories.UserRepository", "class_m_p_z_t_1_1_infrustructure_1_1_repositories_1_1_user_repository.html", null ]
    ] ],
    [ "MPZT.Infrustructure.Services.IUserService", "interface_m_p_z_t_1_1_infrustructure_1_1_services_1_1_i_user_service.html", [
      [ "MPZT.Infrustructure.Services.UserService", "class_m_p_z_t_1_1_infrustructure_1_1_services_1_1_user_service.html", null ]
    ] ],
    [ "MPZT.Infrustructure.ModelDto.LocationDto", "class_m_p_z_t_1_1_infrustructure_1_1_model_dto_1_1_location_dto.html", null ],
    [ "MPZT.GUI.Models.LocationModel", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_location_model.html", null ],
    [ "MPZT.Infrastructure.Test.LocationRepositoryTests", "class_m_p_z_t_1_1_infrastructure_1_1_test_1_1_location_repository_tests.html", null ],
    [ "MPZT.GUI.Models.LocationSearchModel", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_location_search_model.html", null ],
    [ "MPZT.GUI.Models.LoginView", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_login_view.html", null ],
    [ "MembershipProvider", null, [
      [ "MPZT.GUI.CustomAuthentication.CustomMembership", "class_m_p_z_t_1_1_g_u_i_1_1_custom_authentication_1_1_custom_membership.html", null ]
    ] ],
    [ "MembershipUser", null, [
      [ "MPZT.GUI.CustomAuthentication.CustomMembershipUser", "class_m_p_z_t_1_1_g_u_i_1_1_custom_authentication_1_1_custom_membership_user.html", null ]
    ] ],
    [ "MPZT.Infrustructure.NHibernate.NHibernateBase", "class_m_p_z_t_1_1_infrustructure_1_1_n_hibernate_1_1_n_hibernate_base.html", null ],
    [ "MPZT.Program", "class_m_p_z_t_1_1_program.html", null ],
    [ "MPZT.Infrustructure.ModelDto.ProjectDto", "class_m_p_z_t_1_1_infrustructure_1_1_model_dto_1_1_project_dto.html", null ],
    [ "MPZT.Core.Domain.ProjectFile", "class_m_p_z_t_1_1_core_1_1_domain_1_1_project_file.html", null ],
    [ "MPZT.Infrustructure.ModelDto.ProjectFileDto", "class_m_p_z_t_1_1_infrustructure_1_1_model_dto_1_1_project_file_dto.html", null ],
    [ "MPZT.GUI.Models.ProjectFileModel", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_project_file_model.html", null ],
    [ "MPZT.GUI.Models.ProjectModel", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_project_model.html", null ],
    [ "MPZT.Infrastructure.Test.ProjectServiceTests", "class_m_p_z_t_1_1_infrastructure_1_1_test_1_1_project_service_tests.html", null ],
    [ "MPZT.Infrustructure.ModelDto.ProposalDto", "class_m_p_z_t_1_1_infrustructure_1_1_model_dto_1_1_proposal_dto.html", null ],
    [ "MPZT.GUI.Models.ProposalModel", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_proposal_model.html", null ],
    [ "MPZT.Infrastructure.Test.ProposalRepositoryTests", "class_m_p_z_t_1_1_infrastructure_1_1_test_1_1_proposal_repository_tests.html", null ],
    [ "MPZT.Infrastructure.Test.ProposalServiceTests", "class_m_p_z_t_1_1_infrastructure_1_1_test_1_1_proposal_service_tests.html", null ],
    [ "MPZT.GUI.Models.Registration", "class_m_p_z_t_1_1_g_u_i_1_1_models_1_1_registration.html", null ],
    [ "MPZT.GUI.DataAccess.Role", "class_m_p_z_t_1_1_g_u_i_1_1_data_access_1_1_role.html", null ],
    [ "MPZT.Infrustructure.ModelDto.RoleDto", "class_m_p_z_t_1_1_infrustructure_1_1_model_dto_1_1_role_dto.html", null ],
    [ "RoleProvider", null, [
      [ "MPZT.GUI.CustomAuthentication.CustomRole", "class_m_p_z_t_1_1_g_u_i_1_1_custom_authentication_1_1_custom_role.html", null ]
    ] ],
    [ "MPZT.Api.App_Start.RouteConfig", "class_m_p_z_t_1_1_api_1_1_app___start_1_1_route_config.html", null ],
    [ "MPZT.GUI.RouteConfig", "class_m_p_z_t_1_1_g_u_i_1_1_route_config.html", null ],
    [ "MPZT.Infrustructure.Communication.ServiceResponce", "class_m_p_z_t_1_1_infrustructure_1_1_communication_1_1_service_responce.html", null ],
    [ "MPZT.Startup", "class_m_p_z_t_1_1_startup.html", null ],
    [ "MPZT.GUI.DataAccess.User", "class_m_p_z_t_1_1_g_u_i_1_1_data_access_1_1_user.html", null ],
    [ "MPZT.GUI.Logic.UserApi", "class_m_p_z_t_1_1_g_u_i_1_1_logic_1_1_user_api.html", null ],
    [ "MPZT.GUI.Test.UserApiTest", "class_m_p_z_t_1_1_g_u_i_1_1_test_1_1_user_api_test.html", null ],
    [ "MPZT.Infrustructure.ModelDto.UserDto", "class_m_p_z_t_1_1_infrustructure_1_1_model_dto_1_1_user_dto.html", null ],
    [ "MPZT.Infrastructure.Test.UserRepositoryTests", "class_m_p_z_t_1_1_infrastructure_1_1_test_1_1_user_repository_tests.html", null ],
    [ "MPZT.Infrastructure.Test.UserServiceTests", "class_m_p_z_t_1_1_infrastructure_1_1_test_1_1_user_service_tests.html", null ]
];